sonar.projectKey=rust-coding-dojo
sonar.projectName=Rust Coding Dojo
sonar.projectVersion=1.0

# Analyser tous les katas (code exercice uniquement, pas les solutions)
sonar.sources=katas
sonar.exclusions=\
  **/solutions/**,\
  **/target/**,\
  **/Cargo.lock,\
  **/*.md,\
  **/00-setup/**

sonar.language=rust
sonar.sourceEncoding=UTF-8
sonar.host.url=http://172.17.0.1:9000
sonar.token=<SONAR_TOKEN>
