// Auto-generated by tools/generate-katas.cjs — DO NOT EDIT
import type { Kata } from '../types'

export const KATAS: Kata[] = [
  {
    id: 'kata-01-starter-00-rustward-sword',
    title: 'Rustward sword: The Great Programming Quest',
    titleEn: 'Rustward sword: The Great Programming Quest',
    number: 1,
    total: 6,
    difficulty: 'facile',
    concept: 'bases',
    xpReward: 25,
    description: `Welcome, brave adventurer, to the land of Rust! Your quest awaits, but before you embark on your journey, you must prove your worth by mastering the fundamentals of Rust programming.

Your mission is to help a quirky character named Link on his epic adventure through the Link Forest and to complete various basic challenges.

1. **The Mysterious Variables:**`,
    tests: [
      { name: 'no_todo_remaining', description: 'Aucun todo!() restant', check: (c) => !/todo!\s*\(\s*\)/.test(c) },
      { name: 'solution_pattern', description: 'Code non vide', check: (c) => c.trim().length > 0 }
    ],
    starterCode: `fn main() {
    // See README.md
    todo!()
}
`,
    solutionCode: `// Rustward sword: The Great Programming Quest

fn main() {
    // 1. The Mysterious Variables
    let mut link_health: i32 = 100; // Link's health
    let link_stamina: f32 = 75.5; // Link's stamina
    let mut treasure_chests_found: i32 = 0; // Number of treasure chests found
    let friendly_npc_encountered: bool = false; // Whether Link has encountered a friendly NPC

    // 2. Navigating the Forest
    if link_health > 50 {
        println!("Link is healthy and continues his journey.");
    } else if link_health > 25 {
        println!("Link needs to take a break to recover.");
    } else {
        println!("Link needs to find a healing potion to replenish his health.");
    }

    // 3. The Enchanted Loop
    println!("In the clearing, Link observes the magical creatures:");
    for i in 1..=10 {
        match i % 2 {
            0 => println!("{} - Link encounters an even-tempered creature.", i),
            _ => println!("{} - Link encounters an odd-tempered creature.", i),
        }
    }

    // 4. The Wisdom of Functions
    let success = defeat_beast(link_health, link_stamina);
    println!("{}", success);
}

// Function to determine Link's chances of defeating the beast
fn defeat_beast(health: i32, stamina: f32) -> String {
    let chance = health as f32 * stamina / 1000.0; // Simple chance calculation
    if chance > 50.0 {
        "Link defeats the beast with ease!".to_string()
    } else {
        "Link is no match for the beast!".to_string()
    }
}
`,
    hints: [
      `💡 Regarde le README.md dans \`katas/01-starter/00-rustward-sword/\` pour les consignes.`,
      `💡 Consulte la solution dans \`katas/01-starter/00-rustward-sword/solutions/\` si tu bloques.`
    ],
  },
  {
    id: 'kata-01-starter-01-roman-numerals',
    title: 'Roman Numerals',
    titleEn: 'Roman Numerals',
    number: 2,
    total: 6,
    difficulty: 'facile',
    concept: 'bases',
    xpReward: 30,
    description: `This kata is based on (Roman Numerals from Exercism)[https://exercism.org/tracks/rust/exercises/roman-numerals], which source is [https://codingdojo.org/kata/RomanNumerals/].

The final goal is to convert a number from Arabic numerals to Roman numerals. The largest number is MMMCMXCIX (or 3999).`,
    tests: [
      { name: 'no_todo_remaining', description: 'Aucun todo!() restant', check: (c) => !/todo!\s*\(\s*\)/.test(c) },
      { name: 'solution_pattern', description: 'Code non vide', check: (c) => c.trim().length > 0 }
    ],
    starterCode: `use std::fmt::{Display, Formatter, Result};

pub struct Roman;

impl Display for Roman {
    fn fmt(&self, _f: &mut Formatter<'_>) -> Result {
        todo!("Return a roman-numeral string representation of the Roman object");
    }
}

impl From<u32> for Roman {
    fn from(num: u32) -> Self {
        todo!("Construct a Roman object from the '{num}' number");
    }
}

// Some examples to run
fn main() {
    println!("{}", Roman::from(3994));
    println!("{}", Roman::from(3004));
    println!("{}", Roman::from(304));
    println!("{}", Roman::from(1));
    println!("{}", Roman::from(17));
    println!("{}", Roman::from(101));
    println!("{}", Roman::from(121));
    println!("{}", Roman::from(49));
}

// Unit tests
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn number_1_is_i() {
        let input = 1;
        let output = Roman::from(input).to_string();
        let expected = "I";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_2_is_ii() {
        let input = 2;
        let output = Roman::from(input).to_string();
        let expected = "II";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3_is_iii() {
        let input = 3;
        let output = Roman::from(input).to_string();
        let expected = "III";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_4_is_iv() {
        let input = 4;
        let output = Roman::from(input).to_string();
        let expected = "IV";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_5_is_v() {
        let input = 5;
        let output = Roman::from(input).to_string();
        let expected = "V";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_6_is_vi() {
        let input = 6;
        let output = Roman::from(input).to_string();
        let expected = "VI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_9_is_ix() {
        let input = 9;
        let output = Roman::from(input).to_string();
        let expected = "IX";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_16_is_xvi() {
        let input = 16;
        let output = Roman::from(input).to_string();
        let expected = "XVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_27_is_xxvii() {
        let input = 27;
        let output = Roman::from(input).to_string();
        let expected = "XXVII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_48_is_xlviii() {
        let input = 48;
        let output = Roman::from(input).to_string();
        let expected = "XLVIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_49_is_xlix() {
        let input = 49;
        let output = Roman::from(input).to_string();
        let expected = "XLIX";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_59_is_lix() {
        let input = 59;
        let output = Roman::from(input).to_string();
        let expected = "LIX";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_66_is_lxvi() {
        let input = 66;
        let output = Roman::from(input).to_string();
        let expected = "LXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_93_is_xciii() {
        let input = 93;
        let output = Roman::from(input).to_string();
        let expected = "XCIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_141_is_cxli() {
        let input = 141;
        let output = Roman::from(input).to_string();
        let expected = "CXLI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_163_is_clxiii() {
        let input = 163;
        let output = Roman::from(input).to_string();
        let expected = "CLXIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_166_is_clxvi() {
        let input = 166;
        let output = Roman::from(input).to_string();
        let expected = "CLXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_402_is_cdii() {
        let input = 402;
        let output = Roman::from(input).to_string();
        let expected = "CDII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_575_is_dlxxv() {
        let input = 575;
        let output = Roman::from(input).to_string();
        let expected = "DLXXV";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_666_is_dclxvi() {
        let input = 666;
        let output = Roman::from(input).to_string();
        let expected = "DCLXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_911_is_cmxi() {
        let input = 911;
        let output = Roman::from(input).to_string();
        let expected = "CMXI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_1024_is_mxxiv() {
        let input = 1024;
        let output = Roman::from(input).to_string();
        let expected = "MXXIV";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_1666_is_mdclxvi() {
        let input = 1666;
        let output = Roman::from(input).to_string();
        let expected = "MDCLXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3000_is_mmm() {
        let input = 3000;
        let output = Roman::from(input).to_string();
        let expected = "MMM";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3001_is_mmmi() {
        let input = 3001;
        let output = Roman::from(input).to_string();
        let expected = "MMMI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3888_is_mmmdccclxxxviii() {
        let input = 3888;
        let output = Roman::from(input).to_string();
        let expected = "MMMDCCCLXXXVIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3999_is_mmmcmxcix() {
        let input = 3999;
        let output = Roman::from(input).to_string();
        let expected = "MMMCMXCIX";
        assert_eq!(output, expected);
    }
}
`,
    solutionCode: `use std::fmt::{Display, Formatter, Result};

pub struct Roman {
    value: String,
}

impl Display for Roman {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(f, "{}", self.value)
    }
}

impl From<u32> for Roman {
    fn from(mut num: u32) -> Self {
        if num == 0 {
            panic!("There is no zero (0) in the Roman numeral system!");
        }
        // num > 0
        let mut value = String::new();
        while num > 0 {
            // Let's find the next roman num string to append, and its integer value (to subtract from num before the next iteration)
            let appended_str_and_int_val = match num {
                1..=3 => ("I", 1),
                4 => ("IV", 4),
                5..=8 => ("V", 5),
                9 => ("IX", 9),
                10..=39 => ("X", 10),
                40..=49 => ("XL", 40),
                50..=89 => ("L", 50),
                90..=99 => ("XC", 90),
                100..=399 => ("C", 100),
                400..=499 => ("CD", 400),
                500..=899 => ("D", 500),
                900..=999 => ("CM", 900),
                // default case: 1000 and above
                _ => ("M", 1000),
            };

            value += appended_str_and_int_val.0;
            num -= appended_str_and_int_val.1;
        }
        // If we had used a different variable name, say "val", instead of "value" which happens to be the same as the Roman struct field's, the final expression would be "Roman { value: val }" instead of "Roman { value }".
        Roman { value }
    }
}

// Some examples to run
fn main() {
    println!("{}", Roman::from(3994));
    println!("{}", Roman::from(3004));
    println!("{}", Roman::from(304));
    println!("{}", Roman::from(1));
    println!("{}", Roman::from(17));
    println!("{}", Roman::from(101));
    println!("{}", Roman::from(121));
    println!("{}", Roman::from(49));
}

// Unit tests
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn number_1_is_i() {
        let input = 1;
        let output = Roman::from(input).to_string();
        let expected = "I";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_2_is_ii() {
        let input = 2;
        let output = Roman::from(input).to_string();
        let expected = "II";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3_is_iii() {
        let input = 3;
        let output = Roman::from(input).to_string();
        let expected = "III";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_4_is_iv() {
        let input = 4;
        let output = Roman::from(input).to_string();
        let expected = "IV";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_5_is_v() {
        let input = 5;
        let output = Roman::from(input).to_string();
        let expected = "V";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_6_is_vi() {
        let input = 6;
        let output = Roman::from(input).to_string();
        let expected = "VI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_9_is_ix() {
        let input = 9;
        let output = Roman::from(input).to_string();
        let expected = "IX";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_16_is_xvi() {
        let input = 16;
        let output = Roman::from(input).to_string();
        let expected = "XVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_27_is_xxvii() {
        let input = 27;
        let output = Roman::from(input).to_string();
        let expected = "XXVII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_48_is_xlviii() {
        let input = 48;
        let output = Roman::from(input).to_string();
        let expected = "XLVIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_49_is_xlix() {
        let input = 49;
        let output = Roman::from(input).to_string();
        let expected = "XLIX";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_59_is_lix() {
        let input = 59;
        let output = Roman::from(input).to_string();
        let expected = "LIX";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_66_is_lxvi() {
        let input = 66;
        let output = Roman::from(input).to_string();
        let expected = "LXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_93_is_xciii() {
        let input = 93;
        let output = Roman::from(input).to_string();
        let expected = "XCIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_141_is_cxli() {
        let input = 141;
        let output = Roman::from(input).to_string();
        let expected = "CXLI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_163_is_clxiii() {
        let input = 163;
        let output = Roman::from(input).to_string();
        let expected = "CLXIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_166_is_clxvi() {
        let input = 166;
        let output = Roman::from(input).to_string();
        let expected = "CLXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_402_is_cdii() {
        let input = 402;
        let output = Roman::from(input).to_string();
        let expected = "CDII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_575_is_dlxxv() {
        let input = 575;
        let output = Roman::from(input).to_string();
        let expected = "DLXXV";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_666_is_dclxvi() {
        let input = 666;
        let output = Roman::from(input).to_string();
        let expected = "DCLXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_911_is_cmxi() {
        let input = 911;
        let output = Roman::from(input).to_string();
        let expected = "CMXI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_1024_is_mxxiv() {
        let input = 1024;
        let output = Roman::from(input).to_string();
        let expected = "MXXIV";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_1666_is_mdclxvi() {
        let input = 1666;
        let output = Roman::from(input).to_string();
        let expected = "MDCLXVI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3000_is_mmm() {
        let input = 3000;
        let output = Roman::from(input).to_string();
        let expected = "MMM";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3001_is_mmmi() {
        let input = 3001;
        let output = Roman::from(input).to_string();
        let expected = "MMMI";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3888_is_mmmdccclxxxviii() {
        let input = 3888;
        let output = Roman::from(input).to_string();
        let expected = "MMMDCCCLXXXVIII";
        assert_eq!(output, expected);
    }

    #[test]
    fn number_3999_is_mmmcmxcix() {
        let input = 3999;
        let output = Roman::from(input).to_string();
        let expected = "MMMCMXCIX";
        assert_eq!(output, expected);
    }

    #[test]
    #[should_panic]
    fn number_0_is_invalid() {
        let input = 0;
        let output = Roman::from(input).to_string();
        println!(
            "Wrong output: {} (Should have failed because the input (0) is invalid.)",
            output
        );
    }
}
`,
    hints: [
      `💡 Regarde le README.md dans \`katas/01-starter/01-roman-numerals/\` pour les consignes.`,
      `💡 Consulte la solution dans \`katas/01-starter/01-roman-numerals/solutions/\` si tu bloques.`
    ],
  },
  {
    id: 'kata-01-starter-02-rpn-calculator',
    title: 'Text Based RPN calculator',
    titleEn: 'Text Based RPN calculator',
    number: 3,
    total: 6,
    difficulty: 'facile',
    concept: 'bases',
    xpReward: 35,
    description: `RPN : https://en.wikipedia.org/wiki/Reverse_Polish_notation

Build a text based Reverse Polish Notation (RPN) calculator.

In this kata you will develop a simple CLI (Command Line interface) Reverse Polish Notation Calculator.`,
    tests: [
      { name: 'solution_pattern', description: 'Code non vide', check: (c) => c.trim().length > 0 }
    ],
    starterCode: `pub mod cli {
    pub fn print_header() {
        clear_terminal_screen();
        println!("");
        println!("");
        println!("-------------------------------");
        println!(" Welcome to the RPN calculator");
        println!("-------------------------------");
        println!("");
        println!("");
        print_available_commands();
    }

    pub fn print_goodbye_msg() {
        clear_terminal_screen();
        println!("");
        println!("");
        println!("---------------------------------------");
        println!("Thank you for using the RPN calculator.");
        println!("---------------------------------------");
        println!("");
        println!("");
    }

    pub fn print_error_msg() {
        println!("Unknown operation. Available operations are : ");
        print_available_commands();
    }

    pub fn print_operation_error() {
        println!("Unable to perform operation on current stack.");
        print_available_commands();
    }

    pub fn print_available_commands() {
        println!(
            "Input any floating point number. e.g. \\"123.45\\" for it to be added to the LIFO."
        );
        println!("\\"+\\" to add the two last items on the LIFO.");
        println!("\\"-\\" to substract the two last items on the LIFO.");
        println!("\\"*\\" to multiply the two last items on the LIFO.");
        println!("\\"/\\" to divide the two last items on the LIFO.");
        println!("\\"r\\" to reset the program.");
        println!("\\"q\\" to exit the program.");
    }

    pub fn clear_terminal_screen() {
        print!("{esc}c", esc = 27 as char);
    }
}


// Text - Based RPN calculator
// RPN : https://en.wikipedia.org/wiki/Reverse_Polish_notation
//
// Kata for the STARTER package of the Rust coding DOJO
// This kata as a part of the STARTER package targets Rust beginners.
// In this kata, participants will work on the following :
// -> Creating and Using Variables
// -> Control Flow Concepts
// -> Loops
// -> Functions
//
// Instructions
// In this kata you will develop a simple CLI (Command Line interface) Reverse Polish Notation Calculator.
// RPN functions with a last-in first out stack (LIFO) of 64 bits floating point elements.
// Supported operation are:
// - add
// - substract
// - multiply
// - divide
// Users can input numbers to be added to the stack
// Users can input operators (+, -, *, /). An operator input will apply the corresponding operation to the two last operand in the stack.
// User can exit the application by inputting "q"
// User can reset the application by inputting "r"
// Any other input will print an error message
//
// Prerequisites
// The SETUP package must have been completed
// Access to the Rust documentation at https://doc.rust-lang.org/std/index.html
// Acces to the Rust book at https://doc.rust-lang.org/book/

pub mod cli_prints;
pub mod rpn_stack;
use crate::cli_prints::cli;
use crate::rpn_stack::RPNStack;
use std::{io::Write, process::exit};

pub fn print_header() {
    // TODO 1: Print a welcoming message to the user on the command line
    // TODO 2: use the clear_terminal_screen function from the cli module before displaying the welcoming message
    // TODO 3: print the available commands to the user using the cli module
}

fn verify_operands(lifo: &RPNStack) -> bool {
    // TODO 4: verify you have at least 2 operands in the stack using the lifo.length() methods and return a boolean without using the keyword return
    return false;
}

fn get_rpn_calculator_version() -> String {
    let dot: char = '.';
    let major_version: &str = "1";
    let minor_version: Vec<u8> = vec![240, 159, 146, 150]; // Hint '💖';
    let patch_version: u8 = 12;
    // TODO 5: Compute the version number of the RPN_Calculator major.minor.patch and return it
    return "1.0".to_string();
}

fn main() {
    // Main function of the program
    // Initializing variables
    let mut continue_looping: bool = true;
    let mut first_time_running: bool = true;
    let mut is_showing_commands: bool = true;
    let mut stack: RPNStack = RPNStack::new();

    // Main loop
    // TODO 6: Create a loop using continue_looping as a control condition
    {
        // TODO 7: use condition so that only the first time the loop is running, it print the header then just clean the screen using cli::clear_terminal_screen();
        {
            print_header();
        }

        stack.print_stack();
        is_showing_commands = false;

        // Select operation from input
        match get_user_input() {
            Ok(inputs) => {
                apply_inputs_to_stack_and_update_loop_controls(
                    inputs,
                    &mut stack,
                    &mut continue_looping,
                    &mut is_showing_commands,
                    &mut first_time_running,
                );
            } // end of string processing
            Err(_error) => {
                cli::print_error_msg();
                is_showing_commands = true;
            }
        } // end matching the user input
    } // end of main loop

    cli::print_goodbye_msg();
    exit(0);
}

fn get_user_input() -> Result<String, std::io::Error> {
    print!("{} ", get_rpn_calculator_version());
    print!("> ");
    std::io::stdout().flush().unwrap(); // To make sure the prompt is displayed before stdin is read.
                                        // TODO 8: read from the CLI input using the read_line methode from the stdin reference obtained via the std::io prelude into a buffer
                                        // return a Result<String, std::io::Error> based on what you read.
                                        // There should be no warning at compile time ;)
                                        // Hint : you will need a match statement, see the main function for an example
    return Ok("q".to_string());
}

fn apply_inputs_to_stack_and_update_loop_controls(
    inputs: String,
    stack: &mut RPNStack,
    continue_looping: &mut bool,
    is_showing_commands: &mut bool,
    first_time_running: &mut bool,
) {
    // Cast inputs
    if inputs.trim().eq_ignore_ascii_case("+") {
        // Do the add
        if verify_operands(stack) {
            let operand_one = stack.pop().unwrap();
            let operand_two = stack.pop().unwrap();
            (*stack).push(operand_two + operand_one);
        } else {
            // Not enough operand for add operation
            cli::print_operation_error();
            *is_showing_commands = true;
        }
    } else if inputs.trim().eq_ignore_ascii_case("-") {
        // Do the substraction
        if verify_operands(stack) {
            let operand_one = stack.pop().unwrap();
            let operand_two = stack.pop().unwrap();
            stack.push(operand_two - operand_one); // (*stack) not needed as the dot operator add as many dereference as needed to match the signature!
        } else {
            // Not enough operand for substraction operation
            cli::print_operation_error();
            *is_showing_commands = true;
        }
    } else if inputs.trim().eq_ignore_ascii_case("*") {
        // Do the multiply
        if verify_operands(stack) {
            let operand_one = stack.pop().unwrap();
            let operand_two = stack.pop().unwrap();
            stack.push(operand_two * operand_one);
        } else {
            // Not enough operand for multiply operation
            cli::print_operation_error();
            *is_showing_commands = true;
        }
    } else if inputs.trim().eq_ignore_ascii_case("/") {
        // TODO 9: Implement the divide operation
        // Watch out for the divide by zero
    } else if inputs.trim().eq_ignore_ascii_case("q") {
        //exit the program
        *continue_looping = false;
    } else if inputs.trim().eq_ignore_ascii_case("r") {
        //reset the program
        *continue_looping = true;
        *first_time_running = true;
        *is_showing_commands = true;
        // reset stack
        stack.clear();
    } else {
        // If not a  command then the input is a number or just gibberish
        // TODO 10: use a match statement to parse the inputs into a 64 bits float and use the stack.push(number) method to stack it
        // use the following code block as the error match processing
        // Hint : using the trim methode on inputs is mandatory if not parsing fail because of carriage return ;)
        {
            cli::print_error_msg();
            *is_showing_commands = true;
        }
    }
}


pub struct RPNStack {
    lifo: Vec<f64>,
}

impl RPNStack {
    pub fn new() -> Self {
        RPNStack { lifo: Vec::new() }
    }

    pub fn length(&self) -> usize {
        self.lifo.len()
    }

    pub fn pop(&mut self) -> Option<f64> {
        self.lifo.pop()
    }

    pub fn push(&mut self, item: f64) {
        self.lifo.push(item)
    }

    pub fn clear(&mut self) {
        self.lifo.clear();
    }

    pub fn print_stack(&self) {
        println!("RPN LIFO:");
        for item in &self.lifo {
            println!("\\t{}", item);
        }
        println!("");
    }
}
`,
    solutionCode: `pub mod cli {
    pub fn print_header() {
        clear_terminal_screen();
        println!("");
        println!("");
        println!("-------------------------------");
        println!(" Welcome to the RPN calculator");
        println!("-------------------------------");
        println!("");
        println!("");
        print_available_commands();
    }

    pub fn print_goodbye_msg() {
        clear_terminal_screen();
        println!("");
        println!("");
        println!("---------------------------------------");
        println!("Thank you for using the RPN calculator.");
        println!("---------------------------------------");
        println!("");
        println!("");
    }

    pub fn print_error_msg() {
        println!("Unknown operation. Available operations are : ");
        print_available_commands();
    }

    pub fn print_operation_error() {
        println!("Unable to perform operation on current stack.");
        print_available_commands();
    }

    pub fn print_available_commands() {
        println!(
            "Input any floating point number. e.g. \\"123.45\\" for it to be added to the LIFO."
        );
        println!("\\"+\\" to add the two last items on the LIFO.");
        println!("\\"-\\" to substract the two last items on the LIFO.");
        println!("\\"*\\" to multiply the two last items on the LIFO.");
        println!("\\"/\\" to divide the two last items on the LIFO.");
        println!("\\"r\\" to reset the program.");
        println!("\\"q\\" to exit the program.");
    }

    pub fn clear_terminal_screen() {
        print!("{esc}c", esc = 27 as char);
    }
}


// Text - Based RPN calculator
// RPN : https://en.wikipedia.org/wiki/Reverse_Polish_notation
//
// Kata for the STARTER package of the Rust coding DOJO
// This kata as a part of the STARTER package targets Rust beginners.
// In this kata, participants will work on the following :
// -> Creating and Using Variables
// -> Control Flow Concepts
// -> Loops
// -> Functions
//
// Instructions
// In this kata you will develop a simple CLI (Command Line interface) Reverse Polish Notation Calculator.
// RPN functions with a last-in first out stack (LIFO) of 64 bits floating point elements.
// Supported operation are:
// - add
// - substract
// - multiply
// - divide
// Users can input numbers to be added to the stack
// Users can input operators (+, -, *, /). An operator input will apply the corresponding operation to the two last operand in the stack.
// User can exit the application by inputting "q"
// User can reset the application by inputting "r"
// Any other input will print an error message
//
// Prerequisites
// The SETUP package must have been completed
// Access to the Rust documentation at https://doc.rust-lang.org/std/index.html
// Acces to the Rust book at https://doc.rust-lang.org/book/

pub mod cli_prints;
pub mod rpn_stack;
use crate::cli_prints::cli;
use crate::rpn_stack::RPNStack;
use std::{io::Write, process::exit};

pub fn print_header() {
    cli::clear_terminal_screen();
    println!("");
    println!("");
    println!("-------------------------------");
    println!(" Welcome to the RPN calculator");
    println!("-------------------------------");
    println!("");
    println!("");
    cli::print_available_commands();
}

fn verify_operands(lifo: &RPNStack) -> bool {
    lifo.length() >= 2
}

fn get_rpn_calculator_version() -> String {
    let dot: char = '.';
    let major_version: &str = "1";
    let minor_version: Vec<u8> = vec![240, 159, 146, 150]; // Hint '💖';
    let patch_version: u8 = 12;
    let mut version: String = String::from(major_version);
    version.push(dot);
    version.push_str(&String::from_utf8(minor_version).unwrap());
    version.push(dot);
    version.push_str(&patch_version.to_string());
    version
}

fn get_user_input() -> Result<String, std::io::Error> {
    print!("{} ", get_rpn_calculator_version());
    print!("> ");
    std::io::stdout().flush().unwrap(); // To make sure the prompt is displayed before stdin is read.
    let mut buffer = String::new();
    match std::io::stdin().read_line(&mut buffer) {
        Ok(_n) => {
            // OK read, returning the input
            // Check inputs
            Ok(buffer)
        }
        Err(error) => {
            // KO read returning the error
            Err(error)
        }
    }
}

fn main() {
    // Main function of the program
    // Initializing variables
    let mut continue_looping: bool = true;
    let mut first_time_running: bool = true;
    let mut is_showing_commands: bool = true;
    let mut stack: RPNStack = RPNStack::new();

    // Main loop
    while continue_looping {
        if first_time_running {
            print_header();
            first_time_running = false;
        } else if !is_showing_commands {
            cli::clear_terminal_screen();
        }
        stack.print_stack();
        is_showing_commands = false;

        // Select operation from input
        match get_user_input() {
            Ok(inputs) => {
                apply_inputs_to_stack_and_update_loop_controls(
                    inputs,
                    &mut stack,
                    &mut continue_looping,
                    &mut is_showing_commands,
                    &mut first_time_running,
                );
            } // end of string processing
            Err(_error) => {
                cli::print_error_msg();
                is_showing_commands = true;
            }
        } // end matching the user input
    } // end of main loop
    cli::print_goodbye_msg();
    exit(0);
}

fn apply_inputs_to_stack_and_update_loop_controls(
    inputs: String,
    stack: &mut RPNStack,
    continue_looping: &mut bool,
    is_showing_commands: &mut bool,
    first_time_running: &mut bool,
) {
    // Cast inputs
    if inputs.trim().eq_ignore_ascii_case("+") {
        // Do the add
        if verify_operands(stack) {
            let operand_one = stack.pop().unwrap();
            let operand_two = stack.pop().unwrap();
            (*stack).push(operand_two + operand_one);
        } else {
            // Not enough operand for add operation
            cli::print_operation_error();
            *is_showing_commands = true;
        }
    } else if inputs.trim().eq_ignore_ascii_case("-") {
        // Do the substraction
        if verify_operands(stack) {
            let operand_one = stack.pop().unwrap();
            let operand_two = stack.pop().unwrap();
            stack.push(operand_two - operand_one); // (*stack) not needed as the dot operator add as many dereference as needed to match the signature!
        } else {
            // Not enough operand for substraction operation
            cli::print_operation_error();
            *is_showing_commands = true;
        }
    } else if inputs.trim().eq_ignore_ascii_case("*") {
        // Do the multiply
        if verify_operands(stack) {
            let operand_one = stack.pop().unwrap();
            let operand_two = stack.pop().unwrap();
            stack.push(operand_two * operand_one);
        } else {
            // Not enough operand for multiply operation
            cli::print_operation_error();
            *is_showing_commands = true;
        }
    } else if inputs.trim().eq_ignore_ascii_case("/") {
        // Do the divide
        if verify_operands(stack) {
            let operand_one = stack.pop().unwrap();
            let operand_two = stack.pop().unwrap();
            if operand_one != 0.0_f64 {
                stack.push(operand_two / operand_one);
            } else {
                // 0 divide
                // push back the operand into the stack
                stack.push(operand_two);
                stack.push(operand_one);
                cli::print_operation_error();
                *is_showing_commands = true;
            }
        } else {
            // Not enough operand for divide operation
            cli::print_operation_error();
            *is_showing_commands = true;
        }
    } else if inputs.trim().eq_ignore_ascii_case("q") {
        //exit the program
        *continue_looping = false;
    } else if inputs.trim().eq_ignore_ascii_case("r") {
        //reset the program
        *continue_looping = true;
        *first_time_running = true;
        *is_showing_commands = true;
        // reset stack
        stack.clear();
    } else {
        // If not a command then the input is a number or just gibberish
        // using the trim methode on inputs is mandatory if not parsing fail because of carriage return
        match inputs.trim().parse::<f64>() {
            Ok(number) => {
                // pushing the number on the lifo stack
                stack.push(number);
            }
            Err(_error) => {
                // gibberish
                cli::print_error_msg();
                *is_showing_commands = true;
            }
        }
    }
}


pub struct RPNStack {
    lifo: Vec<f64>,
}

impl RPNStack {
    pub fn new() -> Self {
        RPNStack { lifo: Vec::new() }
    }

    pub fn length(&self) -> usize {
        self.lifo.len()
    }

    pub fn pop(&mut self) -> Option<f64> {
        self.lifo.pop()
    }

    pub fn push(&mut self, item: f64) {
        self.lifo.push(item)
    }

    pub fn clear(&mut self) {
        self.lifo.clear();
    }

    pub fn print_stack(&self) {
        println!("RPN LIFO:");
        for item in &self.lifo {
            println!("\\t{}", item);
        }
        println!("");
    }
}
`,
    hints: [
      `💡 Regarde le README.md dans \`katas/01-starter/02-rpn_calculator/\` pour les consignes.`,
      `💡 Consulte la solution dans \`katas/01-starter/02-rpn_calculator/solutions/\` si tu bloques.`
    ],
  },
  {
    id: 'kata-01-starter-03-ownership-borrowing',
    title: 'Ownership Borrowing',
    titleEn: 'Ownership Borrowing',
    number: 4,
    total: 6,
    difficulty: 'moyen',
    concept: 'ownership',
    xpReward: 45,
    description: `TBC

TBC`,
    tests: [
      { name: 'solution_pattern', description: 'Code non vide', check: (c) => c.trim().length > 0 }
    ],
    starterCode: `struct Container {
    str: String,
}

impl Drop for Container {
    fn drop(&mut self) {
        println!("I'm destroyed");
    }
}

fn consume(str_consumed: Container) {
    println!("{}", str_consumed.str);
}

fn main() {
    let str_1 = String::from("string");

    let container = Container { str: str_1 };

    println!("Before function call");
    consume(container);
    println!("End of main scope");
}


// Instruction: Make the program compiling and add the line of code to multiply the element by two

fn mul_two(buffer_s: [i32]) {
    for element in buffer_s {
        // multiply the element by two
    }
}

fn main() {
    let mut buffer_s = [1, 23, 41, 83, 40, 91, 10];
    mul_two(buffer_s);
    println!("{:?}", buffer_s);
}


// Instruction: Make the program compiling by changing instructions orders
fn main() {
    let mut x = 100;
    let y = &mut x;
    let z = &mut x;
    *y += 100;
    *z += 1000;
    assert_eq!(x, 1200);
    println!("Success");
}


// Instruction: Make the program compiling

fn borrowing(element_vec: )
{
    println!("{}", element_vec);
}

fn main() {
    let vec: Vec<String> = vec![String::from("Embedded"), 
        String::from("System"), 
        String::from("Software")
    ];
    borrowing(vec[1]);

    for element in vec {
        println!("{}", element);
    }
}

// Instruction: Make the program compiling and implement borrowing into return_vec function without using a return

fn return_vec(v: Vec<i32>) -> Vec<i32> {
    v.sort();
    v
}

fn main() {
    let v: Vec<i32> = vec![12, 981, 43, 92, 981];
    v = return_vec(v);
    println!("{:?}", v);
}


// Instruction: Make the program compiling without adding/removing references

fn main() {
    let data = "Rust is great!".to_string();

    get_char(data);

    string_uppercase(&data);
}

// Should not take ownership
fn get_char(data: String) -> char {
    data.chars().last().unwrap()
}

// Should take ownership
fn string_uppercase(mut data: &String) {
    data = &data.to_uppercase();

    println!("{}", data);
}


fn longest(x: &str, y: &str) -> &str {
    if x.bytes().len() > y.bytes().len() {
        x
    } else {
        y
    }
}

fn main() {
    let alice = "Alice";
    let bob = "Bob";

    println!("{}", longest(alice, bob));
}


#[derive(Debug)]
struct Person {
    name: &str, // error: expected lifetime parameter
}

fn main() {
    let alice = Person { name: "Alice" };

    println!("alice: {:?}", alice);
}
`,
    solutionCode: `// Instruction: Make the program compiling and add the line of code to multiply the element by two

fn mul_two(buffer_s: &mut [i32]) {
    // We use '&' to use a reference and "mut" to specify that the variable is mutable
    for element in buffer_s {
        *element *= 2; // Unreferencing the variable to update its value
    }
}

fn main() {
    let mut buffer_s = [1, 23, 41, 83, 40, 91, 10];
    mul_two(&mut buffer_s); // We indicate it's a reference and it's mutable
    println!("{:?}", buffer_s);
}


// Instruction: Make the program compiling by changing instructions orders
fn main() {
    let mut x = 100;
    let y = &mut x;
    *y += 100;
    let z = &mut x;
    *z += 1000;
    assert_eq!(x, 1200);
    println!("Success");
}

// Move the Y initialization line above the declaration of the variable z.
// We enter into the rule of the number of references, where if we have a mutable variable, only one reference is allowe
// By moving *y += 100 to line 5, the compiler sees that after this line y is no longer used, so we can modify z with complete peacefully.


// Instruction: Make the program compiling

fn borrowing(element_vec: &String)
// we pass the reference and precise also the type which is a String
{
    println!("{}", element_vec);
}

fn main() {
    let vec: Vec<String> = vec![
        String::from("Embedded"),
        String::from("System"),
        String::from("Software"),
    ];
    borrowing(&vec[1]); // we pass the reference of the vector element

    for element in vec {
        println!("{}", element);
    }
}


// Instruction: Make the program compiling and implement borrowing into return_vec function without using a return

fn return_vec(v: &mut Vec<i32>)
// Sort() changes the vector so must specify it is a mut and of course its reference for the borrowing
{
    v.sort();
}

fn main() {
    let mut v: Vec<i32> = vec![12, 981, 43, 92, 981];
    return_vec(&mut v); // mut and reference
    println!("{:?}", v);
}


// Instruction: Make the program compiling without adding/removing references

fn main() {
    let mut data = "Rust is great!".to_string(); // Like in exercise 4, a method which updates the variable needs the variable to be mutable

    string_uppercase(&mut data); // We change the order so the move operation into get_char is performed at the end
    get_char(data);
}

// Should not take ownership
fn get_char(data: String) -> char {
    data.chars().last().unwrap()
}

// Should take ownership
fn string_uppercase(data: &mut String) {
    let data = &data.to_uppercase(); // To reuse the result, we can simply declare the variable without any data loss or reallocation

    println!("{}", data);
}
`,
    hints: [
      `💡 Ce kata nécessite de comprendre les concepts avancés — relis le README.md.`,
      `💡 Les fichiers solutions dans \`katas/01-starter/03-ownership-borrowing/solutions/\` contiennent la correction.`
    ],
  },
  {
    id: 'kata-02-structure-00-basics',
    title: '00-basics',
    titleEn: '',
    number: 5,
    total: 6,
    difficulty: 'moyen',
    concept: 'structs',
    xpReward: 50,
    description: `Consulte le README.md du kata dans le dossier \`katas/02-structure/00-basics/\``,
    tests: [
      { name: 'no_todo_remaining', description: 'Aucun todo!() restant', check: (c) => !/todo!\s*\(\s*\)/.test(c) },
      { name: 'solution_pattern', description: 'Code non vide', check: (c) => c.trim().length > 0 }
    ],
    starterCode: `/*
 * Section 5 : Combined Exercise
 * - *Exercise 1:* Build a program that manages a list of employees. Each employee has a name, age, and job title (an num). Implement sorting based on age and display the sorted list. Make the struct Employee implements the trait Display.
 * - *Exercise 2:* Extend the employee program to handle promotions. Implement a trait \`Promotable\` with a method to increase the salary, and apply it to employees with specific job titles.
 * - *Exercise 3:* Create a data structure for a competence matrix. Display the employees with Rust skills.
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */


/*
 * Section 1 : Introduction
 * - *Exercise 1:* Define an Enum BookType with some kinds like \`comic\`, \`sf\`, \`novel\` and \`programming\`.
 * - *Exercise 2:* Define a struct \`Book\` with fields for title, author, book type and publication year. Instantiate an instance and print its details
 * - *Exercise 3:* Create a struct \`Library\` containing a vector of \`Book\` instances. Write a function to display all books in the library.
 * - *Exercise 4:* Extend the \`Book\` struct with a method to calculate the age of the book based on the current year. Display the age of each book in the library.
 *
 * Tip: Derive \`Debug\` so we can print \`BookType\` with \`{:?}\`
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */


mod combined;
mod introduction;
mod pattern_matching;
mod string;
mod traits;

fn main() {
    todo!()
}


/*
 * Section 3 : Pattern Matching
 * - *Exercise 1:* Create a function to check if a given number is prime, using pattern matching for different cases (prime, non-prime).
 * - *Exercise 2:* Implement a program that categorizes a list of integers into three groups: positive, negative, and zero.
 * - *Exercise 3:* Define an enum \`Shape\` with variants for Circle and Square. Write a function that calculates the area based on the shape and relevant parameters.
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */


/*
 * Section 2 : String and Vector
 * - *Exercise 1:* Given a string, count the number of vowels (a, e, i, o, u) and print the result.
 * - *Exercise 2:* Write a program that takes two vectors and merges them into a single vector, removing any duplicates.
 * - *Exercise 3:* Implement a function that finds the longest word in a sentence. The sentence is provided as a string, and words are separated by spaces.
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */


/*
 * Section 4 : Basics of Traits
 * - *Exercise 1:* Define a trait \`MathOperation\` with a method to perform a basic arithmetic operation (addition, subtraction, multiplication, etc.). Implement the trait for a custom struct.
 * - *Exercise 2:* Create a generic function that takes a vector of any type implementing the \`Display\` trait and prints each element.
 * - *Exercise 3:* Define a trait \`Sortable\` with a method to sort a vector. Implement the trait for a custom struct that contains a vector of integers. *
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */
`,
    solutionCode: `/**
 * Section 5 : Combined Exercise
 * - *Exercise 1:* Build a program that manages a list of employees. Each employee has a name, age, and job title (an num). Implement sorting based on age and display the sorted list. Make the struct Employee implements the trait Display.
 * - *Exercise 2:* Extend the employee program to handle promotions. Implement a trait \`Promotable\` with a method to increase the salary, and apply it to employees with specific job titles.
 * - *Exercise 3:* Create a data structure for a competence matrix. Display the employees with Rust skills.
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */
use std::collections::HashMap;
use std::fmt;

// Employee struct
#[derive(Debug)]
pub struct Employee {
    pub(crate) name: String,
    pub(crate) age: u32,
    pub(crate) job_title: String,
    pub(crate) salary: f64,
}

// Implement Display trait for Employee
impl fmt::Display for Employee {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Name: {}, Age: {}, Job Title: {}, Salary: {}",
            self.name, self.age, self.job_title, self.salary
        )
    }
}

// Trait for promotable employees
pub trait Promotable {
    fn promote(&mut self);
}

impl Promotable for Employee {
    fn promote(&mut self) {
        match self.job_title.as_str() {
            "Manager" => self.salary *= 1.1,
            "Senior Engineer" => self.salary *= 1.05,
            _ => (),
        }
    }
}

// Competence matrix data structure
pub struct CompetenceMatrix {
    pub skill_matrix: HashMap<String, Vec<Employee>>,
}


/**
 * Section 1 : Introduction
 * - *Exercise 1:* Define an Enum BookType with some kinds like \`comic\`, \`sf\`, \`novel\` and \`programming\`.
 * - *Exercise 2:* Define a struct \`Book\` with fields for title, author, book type and publication year. Instantiate an instance and print its details
 * - *Exercise 3:* Create a struct \`Library\` containing a vector of \`Book\` instances. Write a function to display all books in the library.
 * - *Exercise 4:* Extend the \`Book\` struct with a method to calculate the age of the book based on the current year. Display the age of each book in the library.
 *
 * Tip: Derive \`Debug\` so we can print \`BookType\` with \`{:?}\`
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */

// Section 1: Introduction - Exercise 1
#[derive(Debug)]
pub enum BookType {
    Comic,
    SF,
    Novel,
    Programming,
}

// Section 1: Introduction - Exercise 2
pub struct Book {
    pub title: String,
    pub author: String,
    pub publication_year: u32,
    pub book_type: BookType,
}

// Section 1: Introduction - Exercise 3
pub struct Library {
    pub books: Vec<Book>,
}

impl Library {
    pub fn display_books(&self) {
        for book in &self.books {
            println!(
                "Title: {}, Author: {}, Year: {}, Type: {:?}",
                book.title, book.author, book.publication_year, book.book_type
            );
        }
    }
}

// Section 1: Introduction - Exercise 4
impl Book {
    pub fn calculate_age(&self, current_year: u32) -> u32 {
        current_year - self.publication_year
    }
}


use crate::combined::{CompetenceMatrix, Employee, Promotable};
use crate::introduction::{Book, BookType, Library};
use crate::pattern_matching::{categorize_numbers, is_prime, Shape};
use crate::string::{count_vowels, longest_word, merge_and_remove_duplicates};
use crate::traits::{display_elements, Calculator, CustomStruct, MathOperation, Sortable};
use std::collections::HashMap;
use std::error::Error;
use std::f32::consts;

mod combined;
mod introduction;
mod pattern_matching;
mod string;
mod traits;

fn main() {
    // Section 1: Introduction - Exercise 2
    let book1 = Book {
        title: String::from("The Rust Programming Language"),
        author: String::from("Steve Klabnik and Carol Nichols"),
        publication_year: 2018,
        book_type: BookType::Programming,
    };

    // Section 1: Introduction - Exercise 3
    let library = Library {
        books: vec![
            Book {
                title: String::from("Clean Code"),
                author: String::from("Robert C. Martin"),
                publication_year: 2008,
                book_type: BookType::Programming,
            },
            Book {
                title: String::from("Rust in Action"),
                author: String::from("Tim McNamara"),
                publication_year: 2020,
                book_type: BookType::Programming,
            },
        ],
    };

    // Section 1: Introduction - Exercise 4
    let current_year = 2024;
    let age = book1.calculate_age(current_year);

    // Display Book Details
    println!("Book 1 Details:");
    println!(
        "Title: {}, Author: {}, Year: {}, Type: {:?}",
        book1.title, book1.author, book1.publication_year, book1.book_type
    );
    println!("Age of Book 1: {} years", age);

    // Display Library Books
    println!("\\nLibrary Books:");
    library.display_books();

    // Section 2: Strings and Vectors - Exercise 1
    let input_string = "Hello, Rust!";
    let vowel_count = count_vowels(input_string);
    println!("Vowel Count in '{}': {}", input_string, vowel_count);

    // Section 2: Strings and Vectors - Exercise 2
    let vec1 = vec![1, 2, 3];
    let vec2 = vec![3, 4, 5];
    let merged_vector = merge_and_remove_duplicates(vec1, vec2);
    println!("Merged and Deduplicated Vector: {:?}", merged_vector);

    // Section 2: Strings and Vectors - Exercise 3
    let sentence = "Rust programming is amazing!";
    let longest = longest_word(sentence);
    println!("Longest Word in '{}': {}", sentence, longest);

    // Section 3: Pattern Matching - Exercise 1
    let prime_number = 19;
    if is_prime(prime_number) {
        println!("{} is prime", prime_number);
    } else {
        println!("{} is not prime", prime_number);
    }

    // Section 3: Pattern Matching - Exercise 2
    let numbers_to_categorize = vec![5, -2, 0, 8, -3];
    println!("Categorized Numbers:");
    categorize_numbers(numbers_to_categorize);

    // Section 3: Pattern Matching - Exercise 3
    let circle = Shape::Circle(5.0);
    let square = Shape::Square(4.0);
    println!("Circle Area: {}", circle.calculate_area());
    println!("Square Area: {}", square.calculate_area());

    // Section 4: Basics of Traits - Exercise 1
    let calculator = Calculator;
    let result = calculator.perform_operation(3.0, 7.0);
    println!("Addition Result: {}", result);

    // Section 4: Basics of Traits - Exercise 2
    let display_elements_vector = vec![10.0, 42f32, consts::PI];
    println!("Displaying Elements:");
    display_elements(display_elements_vector);
    let display_elements_vector = vec!["Hello", "world", "!"];
    println!("Displaying Elements:");
    display_elements(display_elements_vector);

    // Section 4: Basics of Traits - Exercise 3
    let mut custom_struct = CustomStruct {
        numbers: vec![3, 1, 4, 1, 5, 9],
    };
    custom_struct.sort();
    println!("Sorted Numbers: {:?}", custom_struct.numbers);

    // Section 5: Combined Exercise - Exercise 1
    let mut employees = vec![
        Employee {
            name: String::from("Alice"),
            age: 30,
            job_title: String::from("Manager"),
            salary: 80000.0,
        },
        Employee {
            name: String::from("Bob"),
            age: 28,
            job_title: String::from("Senior Engineer"),
            salary: 75000.0,
        },
        Employee {
            name: String::from("Charlie"),
            age: 35,
            job_title: String::from("Junior Engineer"),
            salary: 60000.0,
        },
    ];

    // Sort employees by age
    employees.sort_by(|a, b| a.age.cmp(&b.age));

    // Section 5: Combined Exercise - Exercise 2
    // Promote employees

    // Section 5: Combined Exercise - Exercise 3
    // Create competence matrix with skills
    let mut skill_matrix: HashMap<String, Vec<Employee>> = HashMap::new();
    skill_matrix.insert("Rust".to_string(), employees);

    // Display employees with Rust skills
    let mut competence_matrix = CompetenceMatrix { skill_matrix };

    if let Some(rust_employees) = competence_matrix.skill_matrix.get_mut("Rust") {
        println!("Employees with Rust skills:");
        for employee in rust_employees.iter_mut() {
            println!("{}", employee);
            // Section 5: Combined Exercise - Exercise 2
            employee.promote();
        }

        println!("\\nAfter Promotion:");
        for employee in rust_employees.iter() {
            println!("{}", employee);
        }
    } else {
        println!("No employees found with Rust skills.");
    }
}


/**
 * Section 3 : Pattern Matching
 * - *Exercise 1:* Create a function to check if a given number is prime, using pattern matching for different cases (prime, non-prime).
 * - *Exercise 2:* Implement a program that categorizes a list of integers into three groups: positive, negative, and zero.
 * - *Exercise 3:* Define an enum \`Shape\` with variants for Circle and Square. Write a function that calculates the area based on the shape and relevant parameters.
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */
// Section 3: Pattern Matching - Exercise 1
pub fn is_prime(num: u32) -> bool {
    match num {
        0 | 1 => false,
        2 => true,
        n => (2..n).all(|i| n % i != 0),
    }
}

// Section 3: Pattern Matching - Exercise 2
pub fn categorize_numbers(numbers: Vec<i32>) {
    for num in numbers {
        match num {
            n if n > 0 => println!("Positive"),
            n if n < 0 => println!("Negative"),
            _ => println!("Zero"),
        }
    }
}

// Section 3: Pattern Matching - Exercise 3
pub enum Shape {
    Circle(f64),
    Square(f64),
}

impl Shape {
    pub fn calculate_area(&self) -> f64 {
        match self {
            Shape::Circle(radius) => std::f64::consts::PI * radius * radius,
            Shape::Square(side) => side * side,
        }
    }
}


/**
 * Section 2 : String and Vector
 * - *Exercise 1:* Given a string, count the number of vowels (a, e, i, o, u) and print the result.
 * - *Exercise 2:* Write a program that takes two vectors and merges them into a single vector, removing any duplicates.
 * - *Exercise 3:* Implement a function that finds the longest word in a sentence. The sentence is provided as a string, and words are separated by spaces.
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */

// Section 2: Strings and Vectors - Exercise 1
pub fn count_vowels(input_string: &str) -> usize {
    input_string
        .chars()
        .filter(|&c| "aeiouAEIOU".contains(c))
        .count()
}

// Section 2: Strings and Vectors - Exercise 2
pub fn merge_and_remove_duplicates(mut vec1: Vec<i32>, mut vec2: Vec<i32>) -> Vec<i32> {
    vec1.append(&mut vec2);
    vec1.sort();
    vec1.dedup();
    vec1
}

// Section 2: Strings and Vectors - Exercise 3
pub fn longest_word(sentence: &str) -> &str {
    sentence
        .split_whitespace()
        .max_by_key(|&word| word.len())
        .unwrap_or("")
}


/**
 * Section 4 : Basics of Traits
 * - *Exercise 1:* Define a trait \`MathOperation\` with a method to perform a basic arithmetic operation (addition, subtraction, multiplication, etc.). Implement the trait for a custom struct.
 * - *Exercise 2:* Create a generic function that takes a vector of any type implementing the \`Display\` trait and prints each element.
 * - *Exercise 3:* Define a trait \`Sortable\` with a method to sort a vector. Implement the trait for a custom struct that contains a vector of integers. *
 *
 * Define in this module the types, methods and function and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to progressively increase in difficulty.
 */
// Section 4: Basics of Traits - Exercise 1
pub trait MathOperation {
    fn perform_operation(&self, a: f64, b: f64) -> f64;
}

pub struct Calculator;

impl MathOperation for Calculator {
    fn perform_operation(&self, a: f64, b: f64) -> f64 {
        a + b
    }
}

// Section 4: Basics of Traits - Exercise 2
pub fn display_elements<T: std::fmt::Display>(elements: Vec<T>) {
    for element in elements {
        println!("{}", element);
    }
}

// Section 4: Basics of Traits - Exercise 3
pub trait Sortable {
    fn sort(&mut self);
}

pub struct CustomStruct {
    pub numbers: Vec<i32>,
}

impl Sortable for CustomStruct {
    fn sort(&mut self) {
        self.numbers.sort();
    }
}
`,
    hints: [
      `💡 Regarde le README.md dans \`katas/02-structure/00-basics/\` pour les consignes.`
    ],
  },
  {
    id: 'kata-02-structure-01-smart-pointers',
    title: 'Smart Pointers',
    titleEn: 'Smart Pointers',
    number: 6,
    total: 6,
    difficulty: 'difficile',
    concept: 'structs',
    xpReward: 55,
    description: `### Ownership and Memory Management`,
    tests: [
      { name: 'no_todo_remaining', description: 'Aucun todo!() restant', check: (c) => !/todo!\s*\(\s*\)/.test(c) },
      { name: 'solution_pattern', description: 'Code non vide', check: (c) => c.trim().length > 0 }
    ],
    starterCode: `/*
 * Section 1 : Box Smart Pointers
 *
 * - *Exercise 1:* Define an enum \`List\` to implement a singly linked list of integers.
 *     - Use \`Box\` to enable recursive types.
 *     - Implement a method \`prepend\` to add elements to the front of the list.
 *     - Implement a method \`print\` to display the list in order (e.g., 1 -> 2 -> 3 -> Nil).
 *
 * - *Exercise 2:* Create a struct \`BinaryTree\` representing a binary search tree of integers.
 *     - Use \`Box\` for left and right children.
 *     - Implement an \`insert\` method to add new values in BST order.
 *     - Implement a \`print_inorder\` method to traverse and display values in sorted order.
 *
 * - *Exercise 3:* Build a simplified reference counter type \`MyRc<T>\`.
 *     - Internally store the value in a \`Box<T>\`.
 *     - Maintain a manual reference count.
 *     - Provide methods \`new\`, \`clone_ref\` (increment count), and \`count\` (return count).
 *
 * Define in this module the types, methods, and functions, and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to explore real use-cases for Box in Rust.
 */


/*
 * Section 4 : Rc + RefCell Combined
 *
 * - *Exercise 1:* Implement a bidirectional \`Person\` struct using \`Rc<RefCell<T>>\`.
 *     - Each \`Person\` has a name and an optional \`friend\`.
 *     - Use \`Rc<RefCell<Person>>\` to allow two persons to point to each other.
 *     - This creates a cycle: explain how and why it causes a memory leak.
 *
 * - *Exercise 2:* Create a mutable \`GraphNode\` struct.
 *     - Each node has a value and a list of neighbors (\`Vec<Rc<RefCell<GraphNode>>>\`).
 *     - Implement a method to connect two nodes.
 *     - Use \`Weak\` references to break cycles and prevent memory leaks.
 *
 * - *Exercise 3:* Build a trick example showing how \`RefCell\` can panic at runtime.
 *     - Create a struct that borrows mutably twice via \`RefCell\`, triggering a panic.
 *     - Show that Rust's borrow checker doesn't catch it at compile time.
 *
 * These exercises show both the power and the pitfalls of combining Rc and RefCell in Rust.
 */


#![allow(clippy::duplicate_mod)]

mod r#box;
mod combined;
mod rc;
mod refcell;

fn main() {
    todo!()
}


/*
 * Section 2 : Rc & Shared Ownership
 *
 * - *Exercise 1:* Define an enum \`RcList\` to implement a singly linked list of integers.
 *     - Use \`Rc\` to enable shared ownership of list tails.
 *     - Create multiple lists that share the same suffix.
 *     - Implement a method \`print\` to display the list in order (e.g., 1 -> 2 -> 3 -> Nil).
 *
 * - *Exercise 2:* Create a struct \`TreeNode1\` representing a binary tree of integers.
 *     - Use \`Rc\` for left and right children to allow subtree sharing.
 *     - Implement a \`print_inorder\` method to display values in sorted order.
 *     - Demonstrate shared subtrees by cloning shared nodes.
 *
 * - *Exercise 3:* Demonstrate reference counting with \`Rc<T>\`.
 *     - Track how many references exist using \`Rc::strong_count\`.
 *     - Clone an \`Rc\` multiple times and print the reference count at each step.
 *     - Show how scope impacts the count and automatic deallocation.
 *
 * Define in this module the types, methods, and functions, and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to explore real use-cases for Rc in Rust.
 */


/*
 * Section 3 : RefCell & Interior Mutability
 *
 * - *Exercise 1:* Define a struct \`Counter\` that wraps an integer inside a \`RefCell<i32>\`.
 *     - Implement methods \`increment\`, \`get\`, and \`reset\`.
 *     - Demonstrate how interior mutability allows mutation through an immutable reference.
 *
 * - *Exercise 2:* Create a struct \`SharedLog\` with a \`RefCell<Vec<String>>\` to simulate logging.
 *     - Use \`Rc<SharedLog>\` to allow multiple components to push logs into the same buffer.
 *     - Implement a \`log(&self, msg: &str)\` method that appends to the log.
 *     - Implement a \`show(&self)\` method to display the log.
 *
 * - *Exercise 3:* Build a mutable tree structure using \`Rc<RefCell<TreeNode2>>\`.
 *     - Each node holds a value and optional mutable children (\`left\`, \`right\`).
 *     - Implement methods to create nodes, attach children, and print the tree in-order.
 *     - Demonstrate that nodes can be modified from multiple owners thanks to \`RefCell\`.
 *
 * Define in this module the types, methods, and functions, and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to explore real use-cases for RefCell in Rust.
 */
`,
    solutionCode: `/**
 * Section 1 : Box Smart Pointers
 *
 * - *Exercise 1:* Define an enum \`List\` to implement a singly linked list of integers.
 *     - Use \`Box\` to enable recursive types.
 *     - Implement a method \`prepend\` to add elements to the front of the list.
 *     - Implement a method \`print\` to display the list in order (e.g., 1 -> 2 -> 3 -> Nil).
 *
 * - *Exercise 2:* Create a struct \`BinaryTree\` representing a binary search tree of integers.
 *     - Use \`Box\` for left and right children.
 *     - Implement an \`insert\` method to add new values in BST order.
 *     - Implement a \`print_inorder\` method to traverse and display values in sorted order.
 *
 * - *Exercise 3:* Build a simplified reference counter type \`MyRc<T>\`.
 *     - Internally store the value in a \`Box<T>\`.
 *     - Maintain a manual reference count.
 *     - Provide methods \`new\`, \`clone_ref\` (increment count), and \`count\` (return count).
 *
 * Define in this module the types, methods, and functions, and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to explore real use-cases for Box in Rust.
 */

// Section 1: Box Smart Pointers - Exercise 1

pub enum List {
    Cons(i32, Box<List>),
    Nil,
}

impl List {
    pub fn new() -> Self {
        List::Nil
    }

    pub fn prepend(self, value: i32) -> Self {
        List::Cons(value, Box::new(self))
    }

    pub fn print(&self) {
        match self {
            List::Cons(val, next) => {
                print!("{} -> ", val);
                next.print();
            }
            List::Nil => {
                println!("Nil");
            }
        }
    }
}

// Section 1: Box Smart Pointers - Exercise 2

pub struct TreeNode {
    value: i32,
    left: Option<Box<TreeNode>>,
    right: Option<Box<TreeNode>>,
}

impl TreeNode {
    pub fn new(value: i32) -> Self {
        TreeNode {
            value,
            left: None,
            right: None,
        }
    }

    pub fn insert(self: Box<Self>, new_value: i32) -> Box<Self> {
        if new_value < self.value {
            Box::new(TreeNode {
                value: self.value,
                left: Some(if let Some(left) = self.left {
                    left.insert(new_value)
                } else {
                    Box::new(TreeNode::new(new_value))
                }),
                right: self.right,
            })
        } else {
            Box::new(TreeNode {
                value: self.value,
                left: self.left,
                right: Some(if let Some(right) = self.right {
                    right.insert(new_value)
                } else {
                    Box::new(TreeNode::new(new_value))
                }),
            })
        }
    }

    pub fn print_inorder(&self) {
        if let Some(left) = &self.left {
            left.print_inorder();
        }
        print!("{} ", self.value);
        if let Some(right) = &self.right {
            right.print_inorder();
        }
    }
}

// Section 1: Box Smart Pointers - Exercise 3

pub struct MyRc<T> {
    value: Box<T>,
    count: usize,
}

impl<T: Copy> MyRc<T> {
    pub fn new(value: T) -> Self {
        MyRc {
            value: Box::new(value),
            count: 1,
        }
    }

    pub fn clone_ref(&self) -> Self {
        MyRc {
            value: Box::new(*self.value), // clone the inner value if Copy
            count: self.count + 1,
        }
    }

    pub fn count(&self) -> usize {
        self.count
    }

    pub fn get(&self) -> &T {
        &self.value
    }
}


/**
 * Section 4 : Rc + RefCell Combined
 *
 * - *Exercise 1:* Implement a bidirectional \`Person\` struct using \`Rc<RefCell<T>>\`.
 *     - Each \`Person\` has a name and an optional \`friend\`.
 *     - Use \`Rc<RefCell<Person>>\` to allow two persons to point to each other.
 *     - This creates a cycle: explain how and why it causes a memory leak.
 *
 * - *Exercise 2:* Create a mutable \`GraphNode\` struct.
 *     - Each node has a value and a list of neighbors (\`Vec<Rc<RefCell<GraphNode>>>\`).
 *     - Implement a method to connect two nodes.
 *     - Use \`Weak\` references to break cycles and prevent memory leaks.
 *
 * - *Exercise 3:* Build a trick example showing how \`RefCell\` can panic at runtime.
 *     - Create a struct that borrows mutably twice via \`RefCell\`, triggering a panic.
 *     - Show that Rust's borrow checker doesn't catch it at compile time.
 *
 * These exercises show both the power and the pitfalls of combining Rc and RefCell in Rust.
 */
use std::cell::RefCell;
use std::panic;
use std::rc::{Rc, Weak};

// Section 4 : Rc + RefCell Combined - Exercise 1

#[derive(Debug)]
pub struct Person {
    pub name: String,
    pub friend: RefCell<Option<Rc<Person>>>,
}

impl Person {
    pub fn new(name: &str) -> Rc<Self> {
        Rc::new(Person {
            name: name.to_string(),
            friend: RefCell::new(None),
        })
    }

    pub fn befriend(a: &Rc<Person>, b: &Rc<Person>) {
        *a.friend.borrow_mut() = Some(Rc::clone(b));
        *b.friend.borrow_mut() = Some(Rc::clone(a));
    }
}

// Section 4 : Rc + RefCell Combined - Exercise 2

#[derive(Debug)]
pub struct GraphNode {
    pub name: String,
    pub neighbors: RefCell<Vec<Weak<GraphNode>>>,
}

impl GraphNode {
    pub fn new(name: &str) -> Rc<Self> {
        Rc::new(GraphNode {
            name: name.to_string(),
            neighbors: RefCell::new(vec![]),
        })
    }

    pub fn connect(a: &Rc<Self>, b: &Rc<Self>) {
        a.neighbors.borrow_mut().push(Rc::downgrade(b));
        b.neighbors.borrow_mut().push(Rc::downgrade(a));
    }

    pub fn print_neighbors(&self) {
        for weak in self.neighbors.borrow().iter() {
            if let Some(neigh) = weak.upgrade() {
                println!("{} is connected to {}", self.name, neigh.name);
            }
        }
    }
}

// Section 4 : Rc + RefCell Combined - Exercise 3

pub struct Trap {
    value: RefCell<i32>,
}

impl Trap {
    pub fn new(x: i32) -> Self {
        Trap {
            value: RefCell::new(x),
        }
    }

    pub fn double_mut_borrow(&self) {
        let _first = self.value.borrow_mut();
        let _second = self.value.borrow_mut(); // PANIC at the execution
    }
}

pub fn run_trap() {
    let trap = Trap::new(10);
    // This will crash the program with a panic, but that's the point
    trap.double_mut_borrow();
}


use crate::r#box::{List, TreeNode, MyRc};
use crate::rc::{RcList, TreeNode1}
use crate::refcell::TreeNode2
use crate::combined::{Person, GraphNode, Trap, run_trap};
use std::rc::Rc;

mod r#box;
mod rc;
mod refcell;
mod combined;

fn main() {
    
    // Section 1: Box Smart Pointers - Exercise 1
    
    let list = List::new()
        .prepend(3)
        .prepend(2)
        .prepend(1);

    list.print(); // Output: 1 -> 2 -> 3 -> Nil

    // Section 1: Box Smart Pointers - Exercise 2
    
    let tree = Box::new(TreeNode::new(5))
        .insert(3)
        .insert(7)
        .insert(1)
        .insert(4);

    tree.print_inorder(); // Expected output (sorted): 1 3 4 5 7

    // Section 1: Box Smart Pointers - Exercise 3

    let x = MyRc::new(42);
    println!("Count: {}", x.count());

    let y = x.clone_ref();
    println!("Count: {}", y.count());

    println!("Value in y: {}", y.get());

    // Section 2 : Rc & Shared Ownership - Exercise 1

    let shared_tail = Rc::new(RcList::Cons(10, Rc::new(RcList::Cons(20, Rc::new(RcList::Nil)))));

    let list1 = RcList::Cons(1, Rc::clone(&shared_tail));
    let list2 = RcList::Cons(2, Rc::clone(&shared_tail));

    list1.print(); // 1 -> 10 -> 20 -> Nil
    list2.print(); // 2 -> 10 -> 20 -> Nil

    // Section 2 : Rc & Shared Ownership - Exercise 2

    let shared_leaf = Rc::new(TreeNode1::new(42));

    let left = Rc::new(TreeNode1::with_children(1, Some(Rc::clone(&shared_leaf)), None));
    let right = Rc::new(TreeNode1::with_children(2, None, Some(Rc::clone(&shared_leaf))));

    let root = Rc::new(TreeNode1::with_children(0, Some(left), Some(right)));

    TreeNode1::print_inorder(Some(&root)); // Output: 42 1 0 2 42

    // Section 2 : Rc & Shared Ownership - Exercise 3

    rc::demo_rc_counts();

    // Section 3 RefCell & Interior Mutability - Exercise 1

    let counter = refcell::Counter::new(0);
    counter.increment();
    counter.increment();
    println!("Counter: {}", counter.get()); // 2
    counter.reset();
    println!("Counter after reset: {}", counter.get()); // 0

    // Section 3 RefCell & Interior Mutability - Exercise 2

    let logger = refcell::SharedLog::new();
    let logger_clone = Rc::clone(&logger);
    logger.log("App started");
    logger_clone.log("User logged in");
    logger.show();

    // Section 3 RefCell & Interior Mutability - Exercise 3

    let shared_leaf = TreeNode2::new(99);

    let left = TreeNode2::new(1);
    TreeNode2::set_left(&left, Rc::clone(&shared_leaf));

    let right = TreeNode2::new(2);
    TreeNode2::set_right(&right, Rc::clone(&shared_leaf));

    let root = TreeNode2::new(0);
    TreeNode2::set_left(&root, left);
    TreeNode2::set_right(&root, right);

    TreeNode2::print_inorder(Some(root)); // 99 1 0 2 99

    // Section 4 : Rc + RefCell Combined - Exercise 1

    let alice = Person::new("Alice");
    let bob = Person::new("Bob");

    // Create a mutual reference cycle between Alice and Bob
    Person::befriend(&alice, &bob);

    println!("Alice's friend: {:?}", alice.friend.borrow().as_ref().map(|p| &p.name));
    println!("Bob's friend: {:?}", bob.friend.borrow().as_ref().map(|p| &p.name));

    // Show strong reference counts (they stay >1 due to the cycle)
    println!("Alice strong count: {}", Rc::strong_count(&alice));
    println!("Bob strong count: {}", Rc::strong_count(&bob));

    // Even when main ends, these objects will never be freed (memory leak)

    // Section 4 : Rc + RefCell Combined - Exercise 2

    let node_a = GraphNode::new("A");
    let node_b = GraphNode::new("B");
    let node_c = GraphNode::new("C");

    // Connect nodes bidirectionally using Weak references to prevent cycles
    GraphNode::connect(&node_a, &node_b);
    GraphNode::connect(&node_b, &node_c);
    GraphNode::connect(&node_c, &node_a);

    // Print neighbors of each node
    node_a.print_neighbors();
    node_b.print_neighbors();
    node_c.print_neighbors();

    // Section 4 : Rc + RefCell Combined - Exercise 3

    println!("Attempting to trigger a RefCell panic...");

    // This will panic due to double mutable borrow
    combined::run_trap();
}


/**
 * Section 2 : Rc & Shared Ownership
 * 
 * - *Exercise 1:* Define an enum \`RcList\` to implement a singly linked list of integers.
 *     - Use \`Rc\` to enable shared ownership of list tails.
 *     - Create multiple lists that share the same suffix.
 *     - Implement a method \`print\` to display the list in order (e.g., 1 -> 2 -> 3 -> Nil).
 *
 * - *Exercise 2:* Create a struct \`TreeNode1\` representing a binary tree of integers.
 *     - Use \`Rc\` for left and right children to allow subtree sharing.
 *     - Implement a \`print_inorder\` method to display values in sorted order.
 *     - Demonstrate shared subtrees by cloning shared nodes.
 *
 * - *Exercise 3:* Demonstrate reference counting with \`Rc<T>\`.
 *     - Track how many references exist using \`Rc::strong_count\`.
 *     - Clone an \`Rc\` multiple times and print the reference count at each step.
 *     - Show how scope impacts the count and automatic deallocation.
 *
 * Define in this module the types, methods, and functions, and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to explore real use-cases for Rc in Rust.
 */

use std::rc::Rc;

// Section 2 : Rc & Shared Ownership - Exercise 1

pub enum RcList {
    Cons(i32, Rc<RcList>),
    Nil,
}

impl RcList {
    pub fn print(&self) {
        match self {
            RcList::Cons(val, next) => {
                print!("{} -> ", val);
                next.print();
            }
            RcList::Nil => {
                println!("Nil");
            }
        }
    }
}

// Section 2 : Rc & Shared Ownership - Exercise 2

#[derive(Debug)]
pub struct TreeNode1 {
    pub value: i32,
    pub left: Option<Rc<TreeNode1>,
    pub right: Option<Rc<TreeNode1>>,
}

impl TreeNode1 {
    pub fn new(value: i32) -> Self {
        TreeNode1 {
            value,
            left: None,
            right: None,
        }
    }

    pub fn with_children(value: i32, left: Option<Rc<TreeNode1>>, right: Option<Rc<TreeNode1>>) -> Self {
        TreeNode1 { value, left, right }
    }

    pub fn print_inorder(node: Option<&Rc<TreeNode1>>) {
        if let Some(n) = node {
            Self::print_inorder(n.left.as_ref());
            print!("{} ", n.value);
            Self::print_inorder(n.right.as_ref());
        }
    }
}

// Section 2 : Rc & Shared Ownership - Exercise 3

pub fn demo_rc_counts() {
    let data = Rc::new(vec![1, 2, 3]);

    println!("Initial count: {}", Rc::strong_count(&data)); // 1

    let data_clone1 = Rc::clone(&data);
    println!("After clone 1: {}", Rc::strong_count(&data)); // 2

    {
        let data_clone2 = Rc::clone(&data);
        println!("Inside inner scope: {}", Rc::strong_count(&data)); // 3
        println!("data_clone2: {:?}", data_clone2);
    }

    println!("After inner scope: {}", Rc::strong_count(&data)); // 2
    println!("data_clone1: {:?}", data_clone1);
}


/**
 * Section 3 : RefCell & Interior Mutability
 *
 * - *Exercise 1:* Define a struct \`Counter\` that wraps an integer inside a \`RefCell<i32>\`.
 *     - Implement methods \`increment\`, \`get\`, and \`reset\`.
 *     - Demonstrate how interior mutability allows mutation through an immutable reference.
 *
 * - *Exercise 2:* Create a struct \`SharedLog\` with a \`RefCell<Vec<String>>\` to simulate logging.
 *     - Use \`Rc<SharedLog>\` to allow multiple components to push logs into the same buffer.
 *     - Implement a \`log(&self, msg: &str)\` method that appends to the log.
 *     - Implement a \`show(&self)\` method to display the log.
 *
 * - *Exercise 3:* Build a mutable tree structure using \`Rc<RefCell<TreeNode2>>\`.
 *     - Each node holds a value and optional mutable children (\`left\`, \`right\`).
 *     - Implement methods to create nodes, attach children, and print the tree in-order.
 *     - Demonstrate that nodes can be modified from multiple owners thanks to \`RefCell\`.
 *
 * Define in this module the types, methods, and functions, and use them in \`main.rs\`.
 * The exercises in this coding dojo are designed to explore real use-cases for RefCell in Rust.
 */
use std::cell::RefCell;
use std::rc::Rc;

// Section 3 RefCell & Interior Mutability - Exercise 1

pub struct Counter {
    value: RefCell<i32>,
}

impl Counter {
    pub fn new(initial: i32) -> Self {
        Counter {
            value: RefCell::new(initial),
        }
    }

    pub fn increment(&self) {
        *self.value.borrow_mut() += 1;
    }

    pub fn reset(&self) {
        *self.value.borrow_mut() = 0;
    }

    pub fn get(&self) -> i32 {
        *self.value.borrow()
    }
}

// Section 3 RefCell & Interior Mutability - Exercise 2

pub struct SharedLog {
    messages: RefCell<Vec<String>>,
}

impl SharedLog {
    pub fn new() -> Rc<Self> {
        Rc::new(SharedLog {
            messages: RefCell::new(Vec::new()),
        })
    }

    pub fn log(&self, msg: &str) {
        self.messages.borrow_mut().push(msg.to_string());
    }

    pub fn show(&self) {
        for msg in self.messages.borrow().iter() {
            println!("- {}", msg);
        }
    }
}

// Section 3 RefCell & Interior Mutability - Exercise 3

#[derive(Debug)]
pub struct TreeNode2 {
    pub value: i32,
    pub left: Option<Rc<RefCell<TreeNode2>>>,
    pub right: Option<Rc<RefCell<TreeNode2>>>,
}

impl TreeNode2 {
    pub fn new(value: i32) -> Rc<RefCell<Self>> {
        Rc::new(RefCell::new(TreeNode2 {
            value,
            left: None,
            right: None,
        }))
    }

    pub fn set_left(parent: &Rc<RefCell<TreeNode2>>, child: Rc<RefCell<TreeNode2>>) {
        parent.borrow_mut().left = Some(child);
    }

    pub fn set_right(parent: &Rc<RefCell<TreeNode2>>, child: Rc<RefCell<TreeNode2>>) {
        parent.borrow_mut().right = Some(child);
    }

    pub fn print_inorder(node: Option<Rc<RefCell<TreeNode2>>>) {
        if let Some(rc_node) = node {
            let node_ref = rc_node.borrow();
            Self::print_inorder(node_ref.left.clone());
            print!("{} ", node_ref.value);
            Self::print_inorder(node_ref.right.clone());
        }
    }
}
`,
    hints: [
      `💡 Ce kata nécessite de comprendre les concepts avancés — relis le README.md.`,
      `💡 Les fichiers solutions dans \`katas/02-structure/01-smart-pointers/solutions/\` contiennent la correction.`
    ],
  },
]

export function getKataById(id: string): Kata | undefined {
  return KATAS.find(k => k.id === id)
}

export function getKatasByConceptName(concept: string): Kata[] {
  return KATAS.filter(k => k.concept === concept)
}