const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..', '..')
const KATAS_DIR = path.join(ROOT, 'katas')
const OUT_DIR = path.resolve(__dirname, '..', 'src', 'data')
const OUT_FILE = path.join(OUT_DIR, 'katas.generated.ts')

// Mapping de chaque kata vers concept, difficulté, XP
const KATA_MAP = {
  '00-setup/00-install':   { concept: 'bases',      difficulty: 'facile',   xpReward: 10 },
  '00-setup/01-cargo':     { concept: 'bases',      difficulty: 'facile',   xpReward: 10 },
  '00-setup/02-compiler':  { concept: 'bases',      difficulty: 'facile',   xpReward: 15 },
  '01-starter/00-rustward-sword':     { concept: 'bases',      difficulty: 'facile',   xpReward: 25 },
  '01-starter/01-roman-numerals':     { concept: 'bases',      difficulty: 'facile',   xpReward: 30 },
  '01-starter/02-rpn_calculator':     { concept: 'bases',      difficulty: 'facile',   xpReward: 35 },
  '01-starter/03-ownership-borrowing':{ concept: 'ownership',  difficulty: 'moyen',    xpReward: 45 },
  '02-structure/00-basics':           { concept: 'structs',    difficulty: 'moyen',    xpReward: 50 },
  '02-structure/01-smart-pointers':   { concept: 'structs',    difficulty: 'difficile', xpReward: 55 },
}

function collectDirs(root) {
  const dirs = []
  function walk(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const e of entries) {
      if (e.isDirectory()) {
        const full = path.join(dir, e.name)
        const rel = path.relative(KATAS_DIR, full).replace(/\\/g, '/')
        if (fs.existsSync(path.join(full, 'README.md'))) {
          if (rel.split('/').length >= 2) {
            dirs.push({ full, rel })
          }
        }
        walk(full)
      }
    }
  }
  walk(root)
  return dirs
}

function readFileSafe(p) {
  try { return fs.readFileSync(p, 'utf-8') } catch { return '' }
}

function readRustFiles(dir) {
  if (!fs.existsSync(dir)) return ''
  const files = []
  function walk(d) {
    const entries = fs.readdirSync(d, { withFileTypes: true })
    for (const e of entries) {
      const full = path.join(d, e.name)
      if (e.isDirectory()) walk(full)
      else if (e.name.endsWith('.rs')) files.push(readFileSafe(full))
    }
  }
  walk(dir)
  return files.join('\n\n')
}

function parseReadme(readme) {
  const title = (readme.match(/^#\s+(.+)/m) || [])[1] || ''
  const level = (readme.match(/^##\s+Level\s*\/\s*Duration\s*\n+([^\n]+)/im) || [])[1] || ''
  const context = (readme.match(/^##\s+Context\s*\n+([\s\S]*?)(?=\n##\s|$)/im) || [])[1] || ''
  const objective = (readme.match(/^##\s+Objective\s*\n+([\s\S]*?)(?=\n##\s|$)/im) || [])[1] || ''

  let description = ''
  if (context) description += context.trim()
  if (objective) description += '\n\n' + objective.trim()
  description = description.replace(/</g, '&lt;').replace(/>/g, '&gt;')
  description = description.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')

  const tasks = (readme.match(/^##\s+(?:Tasks|Challenges|Instructions)\s*\n+([\s\S]*?)(?=\n##\s|$)/im) || [])[1] || ''
  if (tasks) {
    description += '\n\n' + tasks.replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
  }

  const isBeginner = /beginner/i.test(level)
  const isIntermediate = /intermediate/i.test(level)
  const isExpert = /expert/i.test(level)

  return { title, level, description, isBeginner, isIntermediate, isExpert }
}

function escapeCode(str) {
  return str.replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')
}

function makeId(rel) {
  return 'kata-' + rel.replace(/[^a-z0-9]/gi, '-').replace(/-+/g, '-').replace(/^-|-$/g, '')
}

let count = 0
const kataDirs = collectDirs(KATAS_DIR)
  .filter(d => KATA_MAP[d.rel])
  .sort((a, b) => {
    const order = Object.keys(KATA_MAP)
    return order.indexOf(a.rel) - order.indexOf(b.rel)
  })

const lines = [
  '// Auto-generated by tools/generate-katas.cjs — DO NOT EDIT',
  'import type { Kata } from \'../types\'',
  '',
  'export const KATAS: Kata[] = [',
]

for (const { full, rel } of kataDirs) {
  count++
  const readme = readFileSafe(path.join(full, 'README.md'))
  const parsed = parseReadme(readme)
  const id = makeId(rel)
  const mapping = KATA_MAP[rel]

  // Starter code = all .rs files in src/
  const srcDir = path.join(full, 'src')
  const starterCode = readRustFiles(srcDir) || 'fn main() {\n    // See README.md\n    todo!()\n}'

  // Solution code = all .rs files in solutions/
  const solutionsDir = path.join(full, 'solutions')
  let solutionCode = readRustFiles(solutionsDir)
  if (!solutionCode && rel.startsWith('00-setup')) {
    solutionCode = '' // setup katas have no code
  }

  const desc = parsed.description || `Consulte le README.md du kata dans le dossier \`katas/${rel}/\``

  // Generate tests
  const tests = []
  if (starterCode.includes('todo!()') || starterCode.includes('todo!')) {
    tests.push({ name: 'no_todo_remaining', description: 'Aucun todo!() restant', check: '(c) => !/todo!\\s*\\(\\s*\\)/.test(c)' })
  }
  if (solutionCode) {
    tests.push({ name: 'solution_pattern', description: 'Code non vide', check: '(c) => c.trim().length > 0' })
  }

  const testsJson = tests.map(t =>
    `      { name: '${t.name}', description: '${t.description}', check: ${t.check} }`
  ).join(',\n')

  lines.push(`  {`)
  lines.push(`    id: '${id}',`)
  lines.push(`    title: '${escapeCode(parsed.title || rel.split('/').pop() || '')}',`)
  lines.push(`    titleEn: '${escapeCode(parsed.title || '')}',`)
  lines.push(`    number: ${count},`)
  lines.push(`    total: ${kataDirs.length},`)
  lines.push(`    difficulty: '${mapping.difficulty}',`)
  lines.push(`    concept: '${mapping.concept}',`)
  lines.push(`    xpReward: ${mapping.xpReward},`)
  lines.push(`    description: \`${escapeCode(desc)}\`,`)

  if (tests.length > 0) {
    lines.push(`    tests: [\n${testsJson}\n    ],`)
  } else {
    lines.push(`    tests: [],`)
  }

  lines.push(`    starterCode: \`${escapeCode(starterCode)}\`,`)
  if (solutionCode) {
    lines.push(`    solutionCode: \`${escapeCode(solutionCode)}\`,`)
  } else {
    lines.push(`    solutionCode: '',`)
  }

  // hints
  lines.push(`    hints: [`)
  function escHint(s) {
    return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${')
  }
  const hint1 = escHint(`💡 Regarde le README.md dans \`katas/${rel}/\` pour les consignes.`)
  const hint2 = escHint(`💡 Consulte la solution dans \`katas/${rel}/solutions/\` si tu bloques.`)
  const hint3 = escHint(`💡 Ce kata n\u00e9cessite de comprendre les concepts avanc\u00e9s \u2014 relis le README.md.`)
  const hint4 = escHint(`💡 Les fichiers solutions dans \`katas/${rel}/solutions/\` contiennent la correction.`)
  if (parsed.isBeginner) {
    lines.push(`      \`${hint1}\`,`)
    lines.push(`      \`${hint2}\``)
  } else if (parsed.isIntermediate) {
    lines.push(`      \`${hint3}\`,`)
    lines.push(`      \`${hint4}\``)
  } else {
    lines.push(`      \`${hint1}\``)
  }
  lines.push(`    ],`)

  lines.push(`  },`)
}

lines.push(']')
lines.push('')
lines.push('export function getKataById(id: string): Kata | undefined {')
lines.push('  return KATAS.find(k => k.id === id)')
lines.push('}')
lines.push('')
lines.push('export function getKatasByConceptName(concept: string): Kata[] {')
lines.push('  return KATAS.filter(k => k.concept === concept)')
lines.push('}')

fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf-8')
console.log(`✓ Generated ${count} katas → ${OUT_FILE}`)
