name: Nightly

on:
  schedule:
    - cron: "0 6 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  nightly:
    name: Nightly Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --workspace --exclude ownership-borrowing
      - run: cargo test --workspace --exclude ownership-borrowing
